name: iOS Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  build-ios:
    name: Build iOS Project
    runs-on: macOS-latest
    
    strategy:
      matrix:
        include:
          - xcode_scheme: FLEX
          - xcode_scheme: FLEXTests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List Available Simulators
      run: |
        echo "=== Available simulators ==="
        xcrun simctl list devices | grep -i iphone || echo "No iPhone simulators found"
        echo ""
        echo "=== Available runtimes ==="
        xcrun simctl list runtimes | grep -i ios || echo "No iOS runtimes found"

    - name: List Available Schemes
      run: |
        echo "=== Available schemes in main workspace ==="
        xcodebuild -workspace "FLEX.xcodeproj/project.xcworkspace" -list
        echo ""
        echo "=== Available schemes in example projects ==="
        if [ -d "Example/FLEXample-Cocoapods.xcodeproj" ]; then
          xcodebuild -project "Example/FLEXample-Cocoapods.xcodeproj" -list || true
        fi
        if [ -d "Example/FLEXample-SPM.xcodeproj" ]; then
          xcodebuild -project "Example/FLEXample-SPM.xcodeproj" -list || true
        fi

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Build FLEX Framework
      run: |
        set -o pipefail
        # Build without specific destination, let xcodebuild choose
        xcodebuild -workspace "FLEX.xcodeproj/project.xcworkspace" -scheme ${{ matrix.xcode_scheme }} -sdk iphonesimulator build | xcpretty

    - name: Build Example Projects
      if: matrix.xcode_scheme == 'FLEX'
      run: |
        set -o pipefail
        # Try building example projects if they exist
        if [ -d "Example/FLEXample-Cocoapods.xcodeproj" ]; then
          echo "Building FLEXample-Cocoapods..."
          xcodebuild -project "Example/FLEXample-Cocoapods.xcodeproj" -scheme FLEXample -sdk iphonesimulator build | xcpretty || echo "FLEXample-Cocoapods build failed or scheme not found"
        fi
        if [ -d "Example/FLEXample-SPM.xcodeproj" ]; then
          echo "Building FLEXample-SPM..."
          xcodebuild -project "Example/FLEXample-SPM.xcodeproj" -scheme FLEXample -sdk iphonesimulator build | xcpretty || echo "FLEXample-SPM build failed or scheme not found"
        fi

    - name: List build products
      run: |
        echo "Build completed for scheme: ${{ matrix.xcode_scheme }}"
        find . -name "*.app" -o -name "*.framework" -o -name "*.xctest" | head -20

    - name: Run Tests
      if: matrix.xcode_scheme == 'FLEXTests'
      run: |
        set -o pipefail
        # Test without specific destination
        xcodebuild -workspace "FLEX.xcodeproj/project.xcworkspace" -scheme FLEXTests -sdk iphonesimulator test | xcpretty

    - name: List build products
      run: |
        echo "Build completed for scheme: ${{ matrix.xcode_scheme }}"
        find . -name "*.app" -o -name "*.framework" -o -name "*.xctest" | head -20

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-${{ github.run_number }}-${{ matrix.xcode_scheme }}
        path: |
          build/
          DerivedData/
        retention-days: 7

    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-${{ github.run_number }}
        release_name: Build ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Build to Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*
        file_glob: true
        tag: build-${{ github.run_number }}
        overwrite: true