name: iOS Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  build-ios:
    name: Build iOS Project
    runs-on: macOS-latest
    
    strategy:
      matrix:
        include:
          - xcode_scheme: FLEX
          - xcode_scheme: FLEXample

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify Project Structure
      run: |
        echo "Project structure:"
        find . -name "*.xcworkspace" -o -name "*.xcodeproj" | head -10
        echo ""
        echo "Checking workspace:"
        ls -la FLEX.xcodeproj/project.xcworkspace/
        echo ""
        echo "Available schemes:"
        xcodebuild -workspace "FLEX.xcodeproj/project.xcworkspace" -list

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Build with xcodebuild
      run: |
        set -o pipefail
        xcodebuild -workspace "FLEX.xcodeproj/project.xcworkspace" -scheme ${{ matrix.xcode_scheme }} -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build | xcpretty

    - name: List build products
      run: |
        echo "Build completed for scheme: ${{ matrix.xcode_scheme }}"
        find . -name "*.app" -o -name "*.framework" | head -10

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-${{ matrix.xcode_scheme }}
        path: |
          build/
          DerivedData/
        retention-days: 7

    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-${{ github.run_number }}
        release_name: Build ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Build to Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*
        file_glob: true
        tag: build-${{ github.run_number }}
        overwrite: true