name: iOS Build

on:
  push:
    branches: [master, main, master-3]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  build-ios:
    name: Build iOS Project
    runs-on: macOS-latest
    
    strategy:
      matrix:
        include:
          - xcode_scheme: FLEX

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List Available Simulators
      run: |
        echo "=== Available simulators ==="
        xcrun simctl list devices | grep -i iphone || echo "No iPhone simulators found"
        echo ""
        echo "=== Available runtimes ==="
        xcrun simctl list runtimes | grep -i ios || echo "No iOS runtimes found"
        echo ""
        echo "=== Available schemes in main workspace ==="
        xcodebuild -workspace "FLEX.xcodeproj/project.xcworkspace" -list
        echo ""

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Build FLEX Framework
      run: |
        set -o pipefail
        # Build without specific destination, let xcodebuild choose
        xcodebuild -workspace "FLEX.xcodeproj/project.xcworkspace" -scheme ${{ matrix.xcode_scheme }} -sdk iphonesimulator build | xcpretty

    - name: List build products
      run: |
        echo "Build completed for scheme: ${{ matrix.xcode_scheme }}"
        find . -name "*.app" -o -name "*.framework" -o -name "*.xctest" | head -20
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la

    - name: Upload entire workspace as artifact
      uses: actions/upload-artifact@v4
      with:
        name: workflow-environment
        path: .
        retention-days: 30

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-${{ github.run_number }}
        release_name: Build ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload All Packages
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*
        file_glob: true
        tag: build-${{ github.run_number }}
        overwrite: true
