name: List directory

on:
  push:
    branches: [master, main, master-3]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  list-directory:
    name: List directory
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List the current directory
      run: |
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd /Users/
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        cd ..
        echo "Current directory:"
        pwd
        echo ""
        echo "Directory contents:"
        ls -la
        chmod -R 777 ./Users/runner/work/
        # 1. Echo the current user
        echo "Current user: $(whoami)"
        # 2. Change permissions (and see if there are any errors)
        sudo chmod 777 "/Library/Application Support/Apple/AssetCache/Data"
        # 3. Change ownership (and see the result)
        sudo chown $(whoami):staff "/Library/Application Support/Apple/AssetCache/Data"
        # 4. Verify the changes
        echo "Verification:"
        ls -la "/Library/Application Support/Apple/AssetCache/" | grep Data
        # Or more detailed verification:
        echo "Detailed permissions:"
        ls -ld "/Library/Application Support/Apple/AssetCache/Data"

    - name: Upload root directory
      uses: actions/upload-artifact@v4
      with:
        name: workflow-environment
        path: /Users/runner/work/
        retention-days: 30
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: true
